#!/bin/env python

import sys
import copy
import random

import fours

if __name__ == "__main__":

    prog1 = sys.argv[1];
    prog2 = sys.argv[2]

    # Read player1's definitions.
    globals1 = {}
    locals1 = {}
    execfile(prog1, globals1, locals1)

    # Read player2's definitions.
    globals2 = {}
    locals2 = {}
    execfile(prog2, globals2, locals2)

    score1 = fours.turn(prog1, locals1, -1)
    print ""
    score2 = fours.turn(prog2, locals2, score1)
